export const colors: Record<string, string> = {
    grass: "bg-green-500",
    fire: "bg-orange-500",
    water: "bg-blue-500",
    poison: "bg-purple-500",
    electric: "bg-yellow-400",
    psychic: "bg-pink-500",
    ice: "bg-cyan-400",
    bug: "bg-lime-500",
    normal: "bg-gray-400",
    fighting: "bg-red-700",
    ground: "bg-amber-700",
    flying: "bg-indigo-300",
    rock: "bg-stone-500",
    ghost: "bg-violet-800",
    dragon: "bg-indigo-700",
    dark: "bg-stone-800",
    steel: "bg-slate-400",
    fairy: "bg-pink-300"
}

export const pokemonTypes = [
    { label: "All", value: "" },
    { label: "Bug", value: "bug" },
    { label: "Dark", value: "dark" },
    { label: "Dragon", value: "dragon" },
    { label: "Electric", value: "electric" },
    { label: "Fairy", value: "fairy" },
    { label: "Fighting", value: "fighting" },
    { label: "Fire", value: "fire" },
    { label: "Flying", value: "flying" },
    { label: "Ghost", value: "ghost" },
    { label: "Grass", value: "grass" },
    { label: "Ground", value: "ground" },
    { label: "Ice", value: "ice" },
    { label: "Normal", value: "normal" },
    { label: "Poison", value: "poison" },
    { label: "Psychic", value: "psychic" },
    { label: "Rock", value: "rock" },
    { label: "Steel", value: "steel" },
    { label: "Water", value: "water" },
];